#!/usr/bin/env python
import unittest

# Mandatory variables
top = '../'
out = '../build'

def test(ctx):
    suite = unittest.TestLoader().discover("test/")
    test_runner = unittest.TextTestRunner()
    test_runner.run(suite)
