#!/usr/bin/env python
import unittest
from waflib.extras import autowaf as autowaf

# Mandatory variables
top = '../'
out = '../build'

def build(bld):
    obj = bld(features     = 'c cprogram',
              source       = ['test_looper.c', '../src/looper.c'],
              target       = 'test_looper',
              install_path = None,
              uselib       = '',
              includes     = '../src ../src/protocol ../src/protocol/nanopb')

def test(ctx):
    autowaf.run_tests(ctx, "looper", ['build/test/test_looper'], dirs=['build/test/'])
