# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='slim.proto',
  package='',
  serialized_pb='\n\nslim.proto\"7\n\x14LooperCommandMessage\x12\x1f\n\x07\x63ommand\x18\x01 \x02(\x0e\x32\x0e.LooperCommand*T\n\rLooperCommand\x12\x11\n\rPLAY_OR_PAUSE\x10\x00\x12\n\n\x06RECORD\x10\x01\x12\x0b\n\x07OVERDUB\x10\x02\x12\n\n\x06INSERT\x10\x03\x12\x0b\n\x07REPLACE\x10\x04')

_LOOPERCOMMAND = descriptor.EnumDescriptor(
  name='LooperCommand',
  full_name='LooperCommand',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='PLAY_OR_PAUSE', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RECORD', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OVERDUB', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INSERT', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REPLACE', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=71,
  serialized_end=155,
)


PLAY_OR_PAUSE = 0
RECORD = 1
OVERDUB = 2
INSERT = 3
REPLACE = 4



_LOOPERCOMMANDMESSAGE = descriptor.Descriptor(
  name='LooperCommandMessage',
  full_name='LooperCommandMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='command', full_name='LooperCommandMessage.command', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=14,
  serialized_end=69,
)

_LOOPERCOMMANDMESSAGE.fields_by_name['command'].enum_type = _LOOPERCOMMAND
DESCRIPTOR.message_types_by_name['LooperCommandMessage'] = _LOOPERCOMMANDMESSAGE

class LooperCommandMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOOPERCOMMANDMESSAGE
  
  # @@protoc_insertion_point(class_scope:LooperCommandMessage)

# @@protoc_insertion_point(module_scope)
