/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_slim_2eproto__INCLUDED
#define PROTOBUF_C_slim_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _LooperCommandMessage LooperCommandMessage;


/* --- enums --- */

typedef enum _LooperCommand {
  LOOPER_COMMAND__PLAY_OR_PAUSE = 0,
  LOOPER_COMMAND__RECORD = 1,
  LOOPER_COMMAND__OVERDUB = 2,
  LOOPER_COMMAND__INSERT = 3,
  LOOPER_COMMAND__REPLACE = 4
} LooperCommand;

/* --- messages --- */

struct  _LooperCommandMessage
{
  ProtobufCMessage base;
  LooperCommand command;
};
#define LOOPER_COMMAND_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&looper_command_message__descriptor) \
    , 0 }


/* LooperCommandMessage methods */
void   looper_command_message__init
                     (LooperCommandMessage         *message);
size_t looper_command_message__get_packed_size
                     (const LooperCommandMessage   *message);
size_t looper_command_message__pack
                     (const LooperCommandMessage   *message,
                      uint8_t             *out);
size_t looper_command_message__pack_to_buffer
                     (const LooperCommandMessage   *message,
                      ProtobufCBuffer     *buffer);
LooperCommandMessage *
       looper_command_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   looper_command_message__free_unpacked
                     (LooperCommandMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*LooperCommandMessage_Closure)
                 (const LooperCommandMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    looper_command__descriptor;
extern const ProtobufCMessageDescriptor looper_command_message__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_slim_2eproto__INCLUDED */
