# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='slim.proto',
  package='',
  serialized_pb='\n\nslim.proto\"*\n\x07\x43ommand\x12\x1f\n\x07\x63ommand\x18\x01 \x02(\x0e\x32\x0e.LooperCommand\"\x16\n\x07Setting\x12\x0b\n\x03\x64ry\x18\x01 \x01(\x02\"\x8a\x01\n\rLooperMessage\x12!\n\x04type\x18\x01 \x02(\x0e\x32\x13.LooperMessage.Type\x12\x19\n\x07\x63ommand\x18\x02 \x01(\x0b\x32\x08.Command\x12\x19\n\x07setting\x18\x03 \x01(\x0b\x32\x08.Setting\" \n\x04Type\x12\x0b\n\x07\x43OMMAND\x10\x00\x12\x0b\n\x07SETTING\x10\x01*T\n\rLooperCommand\x12\x11\n\rPLAY_OR_PAUSE\x10\x00\x12\n\n\x06RECORD\x10\x01\x12\x0b\n\x07OVERDUB\x10\x02\x12\n\n\x06INSERT\x10\x03\x12\x0b\n\x07REPLACE\x10\x04')

_LOOPERCOMMAND = descriptor.EnumDescriptor(
  name='LooperCommand',
  full_name='LooperCommand',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='PLAY_OR_PAUSE', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RECORD', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OVERDUB', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INSERT', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REPLACE', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=223,
  serialized_end=307,
)


PLAY_OR_PAUSE = 0
RECORD = 1
OVERDUB = 2
INSERT = 3
REPLACE = 4


_LOOPERMESSAGE_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='LooperMessage.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='COMMAND', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SETTING', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=189,
  serialized_end=221,
)


_COMMAND = descriptor.Descriptor(
  name='Command',
  full_name='Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='command', full_name='Command.command', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=14,
  serialized_end=56,
)


_SETTING = descriptor.Descriptor(
  name='Setting',
  full_name='Setting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='dry', full_name='Setting.dry', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=58,
  serialized_end=80,
)


_LOOPERMESSAGE = descriptor.Descriptor(
  name='LooperMessage',
  full_name='LooperMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='LooperMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='command', full_name='LooperMessage.command', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='setting', full_name='LooperMessage.setting', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LOOPERMESSAGE_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=83,
  serialized_end=221,
)

_COMMAND.fields_by_name['command'].enum_type = _LOOPERCOMMAND
_LOOPERMESSAGE.fields_by_name['type'].enum_type = _LOOPERMESSAGE_TYPE
_LOOPERMESSAGE.fields_by_name['command'].message_type = _COMMAND
_LOOPERMESSAGE.fields_by_name['setting'].message_type = _SETTING
_LOOPERMESSAGE_TYPE.containing_type = _LOOPERMESSAGE;
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['Setting'] = _SETTING
DESCRIPTOR.message_types_by_name['LooperMessage'] = _LOOPERMESSAGE

class Command(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMAND
  
  # @@protoc_insertion_point(class_scope:Command)

class Setting(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SETTING
  
  # @@protoc_insertion_point(class_scope:Setting)

class LooperMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOOPERMESSAGE
  
  # @@protoc_insertion_point(class_scope:LooperMessage)

# @@protoc_insertion_point(module_scope)
