/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_slim_2eproto__INCLUDED
#define PROTOBUF_C_slim_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _SlimMessage SlimMessage;
typedef struct _SlimMessage__Looper SlimMessage__Looper;
typedef struct _SlimMessage__Looper__Setting SlimMessage__Looper__Setting;
typedef struct _SlimMessage__Global SlimMessage__Global;
typedef struct _SlimMessage__Global__Setting SlimMessage__Global__Setting;


/* --- enums --- */

typedef enum _SlimMessage__Looper__Setting__Name {
  SLIM_MESSAGE__LOOPER__SETTING__NAME__DRY = 0,
  SLIM_MESSAGE__LOOPER__SETTING__NAME__WET = 1
} SlimMessage__Looper__Setting__Name;
typedef enum _SlimMessage__Looper__Command {
  SLIM_MESSAGE__LOOPER__COMMAND__SET = 0,
  SLIM_MESSAGE__LOOPER__COMMAND__PAUSE = 1,
  SLIM_MESSAGE__LOOPER__COMMAND__RECORD = 2,
  SLIM_MESSAGE__LOOPER__COMMAND__OVERDUB = 3,
  SLIM_MESSAGE__LOOPER__COMMAND__INSERT = 4,
  SLIM_MESSAGE__LOOPER__COMMAND__REPLACE = 5
} SlimMessage__Looper__Command;
typedef enum _SlimMessage__Global__Setting__Name {
  SLIM_MESSAGE__GLOBAL__SETTING__NAME__DRY = 0,
  SLIM_MESSAGE__GLOBAL__SETTING__NAME__WET = 1
} SlimMessage__Global__Setting__Name;
typedef enum _SlimMessage__Global__Command {
  SLIM_MESSAGE__GLOBAL__COMMAND__SET = 0,
  SLIM_MESSAGE__GLOBAL__COMMAND__QUIT = 1
} SlimMessage__Global__Command;
typedef enum _SlimMessage__Type {
  SLIM_MESSAGE__TYPE__LOOPER = 0,
  SLIM_MESSAGE__TYPE__GLOBAL = 1
} SlimMessage__Type;

/* --- messages --- */

struct  _SlimMessage__Looper__Setting
{
  ProtobufCMessage base;
  SlimMessage__Looper__Setting__Name name;
  float value;
};
#define SLIM_MESSAGE__LOOPER__SETTING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&slim_message__looper__setting__descriptor) \
    , 0, 0 }


struct  _SlimMessage__Looper
{
  ProtobufCMessage base;
  uint32_t loop_number;
  SlimMessage__Looper__Command command;
  size_t n_settings;
  SlimMessage__Looper__Setting **settings;
};
#define SLIM_MESSAGE__LOOPER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&slim_message__looper__descriptor) \
    , 0, 0, 0,NULL }


struct  _SlimMessage__Global__Setting
{
  ProtobufCMessage base;
  SlimMessage__Global__Setting__Name name;
  float value;
};
#define SLIM_MESSAGE__GLOBAL__SETTING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&slim_message__global__setting__descriptor) \
    , 0, 0 }


struct  _SlimMessage__Global
{
  ProtobufCMessage base;
  SlimMessage__Global__Command command;
  size_t n_settings;
  SlimMessage__Global__Setting **settings;
};
#define SLIM_MESSAGE__GLOBAL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&slim_message__global__descriptor) \
    , 0, 0,NULL }


struct  _SlimMessage
{
  ProtobufCMessage base;
  SlimMessage__Type type;
  SlimMessage__Looper *looper;
  SlimMessage__Global *global;
};
#define SLIM_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&slim_message__descriptor) \
    , 0, NULL, NULL }


/* SlimMessage__Looper__Setting methods */
void   slim_message__looper__setting__init
                     (SlimMessage__Looper__Setting         *message);
/* SlimMessage__Looper methods */
void   slim_message__looper__init
                     (SlimMessage__Looper         *message);
/* SlimMessage__Global__Setting methods */
void   slim_message__global__setting__init
                     (SlimMessage__Global__Setting         *message);
/* SlimMessage__Global methods */
void   slim_message__global__init
                     (SlimMessage__Global         *message);
/* SlimMessage methods */
void   slim_message__init
                     (SlimMessage         *message);
size_t slim_message__get_packed_size
                     (const SlimMessage   *message);
size_t slim_message__pack
                     (const SlimMessage   *message,
                      uint8_t             *out);
size_t slim_message__pack_to_buffer
                     (const SlimMessage   *message,
                      ProtobufCBuffer     *buffer);
SlimMessage *
       slim_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   slim_message__free_unpacked
                     (SlimMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SlimMessage__Looper__Setting_Closure)
                 (const SlimMessage__Looper__Setting *message,
                  void *closure_data);
typedef void (*SlimMessage__Looper_Closure)
                 (const SlimMessage__Looper *message,
                  void *closure_data);
typedef void (*SlimMessage__Global__Setting_Closure)
                 (const SlimMessage__Global__Setting *message,
                  void *closure_data);
typedef void (*SlimMessage__Global_Closure)
                 (const SlimMessage__Global *message,
                  void *closure_data);
typedef void (*SlimMessage_Closure)
                 (const SlimMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor slim_message__descriptor;
extern const ProtobufCMessageDescriptor slim_message__looper__descriptor;
extern const ProtobufCMessageDescriptor slim_message__looper__setting__descriptor;
extern const ProtobufCEnumDescriptor    slim_message__looper__setting__name__descriptor;
extern const ProtobufCEnumDescriptor    slim_message__looper__command__descriptor;
extern const ProtobufCMessageDescriptor slim_message__global__descriptor;
extern const ProtobufCMessageDescriptor slim_message__global__setting__descriptor;
extern const ProtobufCEnumDescriptor    slim_message__global__setting__name__descriptor;
extern const ProtobufCEnumDescriptor    slim_message__global__command__descriptor;
extern const ProtobufCEnumDescriptor    slim_message__type__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_slim_2eproto__INCLUDED */
