/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.5-dev at Wed Dec 11 10:03:04 2013. */

#include "slim.pb.h"



const pb_field_t SlimMessage_fields[4] = {
    PB_FIELD2(  1, ENUM    , REQUIRED, STATIC, FIRST, SlimMessage, type, type, 0),
    PB_FIELD2(  2, MESSAGE , OPTIONAL, STATIC, OTHER, SlimMessage, looper, type, &SlimMessage_Looper_fields),
    PB_FIELD2(  3, MESSAGE , OPTIONAL, STATIC, OTHER, SlimMessage, global, looper, &SlimMessage_Global_fields),
    PB_LAST_FIELD
};

const pb_field_t SlimMessage_Looper_fields[4] = {
    PB_FIELD2(  1, UINT32  , REQUIRED, STATIC, FIRST, SlimMessage_Looper, loop_number, loop_number, 0),
    PB_FIELD2(  2, ENUM    , REQUIRED, STATIC, OTHER, SlimMessage_Looper, command, loop_number, 0),
    PB_FIELD2(  3, MESSAGE , REPEATED, CALLBACK, OTHER, SlimMessage_Looper, settings, command, &SlimMessage_Looper_Setting_fields),
    PB_LAST_FIELD
};

const pb_field_t SlimMessage_Looper_Setting_fields[3] = {
    PB_FIELD2(  1, ENUM    , REQUIRED, STATIC, FIRST, SlimMessage_Looper_Setting, name, name, 0),
    PB_FIELD2(  2, FLOAT   , REQUIRED, STATIC, OTHER, SlimMessage_Looper_Setting, value, name, 0),
    PB_LAST_FIELD
};

const pb_field_t SlimMessage_Global_fields[3] = {
    PB_FIELD2(  2, ENUM    , REQUIRED, STATIC, FIRST, SlimMessage_Global, command, command, 0),
    PB_FIELD2(  3, MESSAGE , REPEATED, CALLBACK, OTHER, SlimMessage_Global, settings, command, &SlimMessage_Global_Setting_fields),
    PB_LAST_FIELD
};

const pb_field_t SlimMessage_Global_Setting_fields[3] = {
    PB_FIELD2(  1, ENUM    , REQUIRED, STATIC, FIRST, SlimMessage_Global_Setting, name, name, 0),
    PB_FIELD2(  2, FLOAT   , REQUIRED, STATIC, OTHER, SlimMessage_Global_Setting, value, name, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
STATIC_ASSERT((pb_membersize(SlimMessage, looper) < 256 && pb_membersize(SlimMessage, global) < 256 && pb_membersize(SlimMessage_Looper, settings) < 256 && pb_membersize(SlimMessage_Global, settings) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_SlimMessage_SlimMessage_Looper_SlimMessage_Looper_Setting_SlimMessage_Global_SlimMessage_Global_Setting)
#endif

#if !defined(PB_FIELD_32BIT)
STATIC_ASSERT((pb_membersize(SlimMessage, looper) < 65536 && pb_membersize(SlimMessage, global) < 65536 && pb_membersize(SlimMessage_Looper, settings) < 65536 && pb_membersize(SlimMessage_Global, settings) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_SlimMessage_SlimMessage_Looper_SlimMessage_Looper_Setting_SlimMessage_Global_SlimMessage_Global_Setting)
#endif

