/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.5-dev at Wed Dec 11 10:03:04 2013. */

#ifndef _PB_SLIM_PB_H_
#define _PB_SLIM_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _SlimMessage_Type {
    SlimMessage_Type_LOOPER = 0,
    SlimMessage_Type_GLOBAL = 1
} SlimMessage_Type;

typedef enum _SlimMessage_Looper_Command {
    SlimMessage_Looper_Command_SET = 0,
    SlimMessage_Looper_Command_PAUSE = 1,
    SlimMessage_Looper_Command_RECORD = 2,
    SlimMessage_Looper_Command_OVERDUB = 3,
    SlimMessage_Looper_Command_INSERT = 4,
    SlimMessage_Looper_Command_REPLACE = 5
} SlimMessage_Looper_Command;

typedef enum _SlimMessage_Looper_Setting_Name {
    SlimMessage_Looper_Setting_Name_DRY = 0,
    SlimMessage_Looper_Setting_Name_WET = 1
} SlimMessage_Looper_Setting_Name;

typedef enum _SlimMessage_Global_Command {
    SlimMessage_Global_Command_SET = 0,
    SlimMessage_Global_Command_QUIT = 1
} SlimMessage_Global_Command;

typedef enum _SlimMessage_Global_Setting_Name {
    SlimMessage_Global_Setting_Name_DRY = 0,
    SlimMessage_Global_Setting_Name_WET = 1
} SlimMessage_Global_Setting_Name;

/* Struct definitions */
typedef struct _SlimMessage_Global {
    SlimMessage_Global_Command command;
    pb_callback_t settings;
} SlimMessage_Global;

typedef struct _SlimMessage_Global_Setting {
    SlimMessage_Global_Setting_Name name;
    float value;
} SlimMessage_Global_Setting;

typedef struct _SlimMessage_Looper {
    uint32_t loop_number;
    SlimMessage_Looper_Command command;
    pb_callback_t settings;
} SlimMessage_Looper;

typedef struct _SlimMessage_Looper_Setting {
    SlimMessage_Looper_Setting_Name name;
    float value;
} SlimMessage_Looper_Setting;

typedef struct _SlimMessage {
    SlimMessage_Type type;
    bool has_looper;
    SlimMessage_Looper looper;
    bool has_global;
    SlimMessage_Global global;
} SlimMessage;

/* Default values for struct fields */

/* Field tags (for use in manual encoding/decoding) */
#define SlimMessage_Global_command_tag           2
#define SlimMessage_Global_settings_tag          3
#define SlimMessage_Global_Setting_name_tag      1
#define SlimMessage_Global_Setting_value_tag     2
#define SlimMessage_Looper_loop_number_tag       1
#define SlimMessage_Looper_command_tag           2
#define SlimMessage_Looper_settings_tag          3
#define SlimMessage_Looper_Setting_name_tag      1
#define SlimMessage_Looper_Setting_value_tag     2
#define SlimMessage_type_tag                     1
#define SlimMessage_looper_tag                   2
#define SlimMessage_global_tag                   3

/* Struct field encoding specification for nanopb */
extern const pb_field_t SlimMessage_fields[4];
extern const pb_field_t SlimMessage_Looper_fields[4];
extern const pb_field_t SlimMessage_Looper_Setting_fields[3];
extern const pb_field_t SlimMessage_Global_fields[3];
extern const pb_field_t SlimMessage_Global_Setting_fields[3];

/* Maximum encoded size of messages (where known) */
#define SlimMessage_Looper_Setting_size          11
#define SlimMessage_Global_Setting_size          11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
