/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "slim.pb-c.h"
void   command__init
                     (Command         *message)
{
  static Command init_value = COMMAND__INIT;
  *message = init_value;
}
size_t command__get_packed_size
                     (const Command *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t command__pack
                     (const Command *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t command__pack_to_buffer
                     (const Command *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Command *
       command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Command *)
     protobuf_c_message_unpack (&command__descriptor,
                                allocator, len, data);
}
void   command__free_unpacked
                     (Command *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   setting__init
                     (Setting         *message)
{
  static Setting init_value = SETTING__INIT;
  *message = init_value;
}
size_t setting__get_packed_size
                     (const Setting *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &setting__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t setting__pack
                     (const Setting *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &setting__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t setting__pack_to_buffer
                     (const Setting *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &setting__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Setting *
       setting__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Setting *)
     protobuf_c_message_unpack (&setting__descriptor,
                                allocator, len, data);
}
void   setting__free_unpacked
                     (Setting *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &setting__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   looper_message__init
                     (LooperMessage         *message)
{
  static LooperMessage init_value = LOOPER_MESSAGE__INIT;
  *message = init_value;
}
size_t looper_message__get_packed_size
                     (const LooperMessage *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &looper_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t looper_message__pack
                     (const LooperMessage *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &looper_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t looper_message__pack_to_buffer
                     (const LooperMessage *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &looper_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LooperMessage *
       looper_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LooperMessage *)
     protobuf_c_message_unpack (&looper_message__descriptor,
                                allocator, len, data);
}
void   looper_message__free_unpacked
                     (LooperMessage *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &looper_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor command__field_descriptors[1] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Command, command),
    &looper_command__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned command__field_indices_by_name[] = {
  0,   /* field[0] = command */
};
static const ProtobufCIntRange command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor command__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Command",
  "Command",
  "Command",
  "",
  sizeof(Command),
  1,
  command__field_descriptors,
  command__field_indices_by_name,
  1,  command__number_ranges,
  (ProtobufCMessageInit) command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor setting__field_descriptors[1] =
{
  {
    "dry",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    PROTOBUF_C_OFFSETOF(Setting, has_dry),
    PROTOBUF_C_OFFSETOF(Setting, dry),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned setting__field_indices_by_name[] = {
  0,   /* field[0] = dry */
};
static const ProtobufCIntRange setting__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor setting__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Setting",
  "Setting",
  "Setting",
  "",
  sizeof(Setting),
  1,
  setting__field_descriptors,
  setting__field_indices_by_name,
  1,  setting__number_ranges,
  (ProtobufCMessageInit) setting__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue looper_message__type__enum_values_by_number[2] =
{
  { "COMMAND", "LOOPER_MESSAGE__TYPE__COMMAND", 0 },
  { "SETTING", "LOOPER_MESSAGE__TYPE__SETTING", 1 },
};
static const ProtobufCIntRange looper_message__type__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex looper_message__type__enum_values_by_name[2] =
{
  { "COMMAND", 0 },
  { "SETTING", 1 },
};
const ProtobufCEnumDescriptor looper_message__type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "LooperMessage.Type",
  "Type",
  "LooperMessage__Type",
  "",
  2,
  looper_message__type__enum_values_by_number,
  2,
  looper_message__type__enum_values_by_name,
  1,
  looper_message__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor looper_message__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LooperMessage, type),
    &looper_message__type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LooperMessage, command),
    &command__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "setting",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LooperMessage, setting),
    &setting__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned looper_message__field_indices_by_name[] = {
  1,   /* field[1] = command */
  2,   /* field[2] = setting */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange looper_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor looper_message__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "LooperMessage",
  "LooperMessage",
  "LooperMessage",
  "",
  sizeof(LooperMessage),
  3,
  looper_message__field_descriptors,
  looper_message__field_indices_by_name,
  1,  looper_message__number_ranges,
  (ProtobufCMessageInit) looper_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue looper_command__enum_values_by_number[5] =
{
  { "PLAY_OR_PAUSE", "LOOPER_COMMAND__PLAY_OR_PAUSE", 0 },
  { "RECORD", "LOOPER_COMMAND__RECORD", 1 },
  { "OVERDUB", "LOOPER_COMMAND__OVERDUB", 2 },
  { "INSERT", "LOOPER_COMMAND__INSERT", 3 },
  { "REPLACE", "LOOPER_COMMAND__REPLACE", 4 },
};
static const ProtobufCIntRange looper_command__value_ranges[] = {
{0, 0},{0, 5}
};
const ProtobufCEnumValueIndex looper_command__enum_values_by_name[5] =
{
  { "INSERT", 3 },
  { "OVERDUB", 2 },
  { "PLAY_OR_PAUSE", 0 },
  { "RECORD", 1 },
  { "REPLACE", 4 },
};
const ProtobufCEnumDescriptor looper_command__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "LooperCommand",
  "LooperCommand",
  "LooperCommand",
  "",
  5,
  looper_command__enum_values_by_number,
  5,
  looper_command__enum_values_by_name,
  1,
  looper_command__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
